import { config } from "./config.js";
import { getZohoAccessToken } from "./oauth.js";
import { getProviderToken,saveProviderToken } from "./tokenStore.js";
async function req(path,{method="GET",query={},body}={}){const a=await getZohoAccessToken(),t=await getProviderToken("zoho"),u=new URL(path,`${t?.apiDomain||config.zoho.apiDomain}/`);for(const[k,v]of Object.entries(query))if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v));const h={Authorization:`Zoho-oauthtoken ${a}`,Accept:"application/json"};if(body!==undefined)h["Content-Type"]="application/json";const r=await fetch(u,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)}),txt=await r.text();let d;try{d=JSON.parse(txt)}catch{d={raw:txt}}if(!r.ok||typeof d.code==="number"&&d.code!==0)throw new Error(`Zoho API failed: HTTP ${r.status} ${JSON.stringify(d)}`);return d;}
export async function listZohoOrganizations(){return (await req("/books/v3/organizations")).organizations||[];}
export async function selectZohoOrganization(id){const token=await getProviderToken("zoho"),os=await listZohoOrganizations(),o=os.find(x=>String(x.organization_id)===String(id));if(!o)throw new Error("Zoho organization not found.");await saveProviderToken("zoho",{...token,organizationId:String(o.organization_id),organizationName:o.name});return o;}
export async function listExistingZohoContactNames(id){const set=new Set();let page=1;while(true){const d=await req("/books/v3/contacts",{query:{organization_id:id,page,per_page:200}});for(const c of d.contacts||[])if(c.contact_name)set.add(String(c.contact_name).trim().toLowerCase());if(!d.page_context?.has_more_page||!(d.contacts||[]).length)break;page++;}return set;}
function payload(c){const a=(c.Addresses||[]).find(x=>x.AddressType==="STREET")||(c.Addresses||[])[0]||{},p=(c.Phones||[]).find(x=>x.PhoneType==="DEFAULT")||(c.Phones||[])[0]||{},cp=(c.ContactPersons||[])[0]||{};const x={contact_name:String(c.Name||"").trim(),contact_type:c.IsSupplier&&!c.IsCustomer?"vendor":"customer",reference_number:String(c.ContactID||"").slice(0,50),billing_address:{address:a.AddressLine1||"",city:a.City||"",state:a.Region||"",zip:a.PostalCode||"",country:a.Country||""},contact_persons:[{first_name:c.FirstName||cp.FirstName||"",last_name:c.LastName||cp.LastName||"",email:c.EmailAddress||cp.EmailAddress||"",phone:p.PhoneNumber||cp.Phone||"",is_primary_contact:true}]};if(!x.contact_name)return null;if(!Object.values(x.billing_address).some(Boolean))delete x.billing_address;return x;}
export async function importContactsToZoho(id,contacts,{skipExisting=true}={}){const existing=skipExisting?await listExistingZohoContactNames(id):new Set(),results=[];let imported=0,skipped=0,failed=0;for(const c of contacts){const name=String(c.Name||"").trim();if(!name){skipped++;results.push({name,status:"skipped",reason:"Missing name"});continue;}if(skipExisting&&existing.has(name.toLowerCase())){skipped++;results.push({name,status:"skipped",reason:"Already exists"});continue;}try{const d=await req("/books/v3/contacts",{method:"POST",query:{organization_id:id},body:payload(c)});imported++;existing.add(name.toLowerCase());results.push({name,status:"imported",contactId:d.contact?.contact_id||null});}catch(e){failed++;results.push({name,status:"failed",error:e.message});}}return{imported,skipped,failed,results};}
